# Battery-Level wird über Bluetooth gemeldet (Standard-mäßig sowieso meist an, schadet aber nicht es explizit zu setzen)
CONFIG_ZMK_BATTERY_REPORTING=y
 
# Deep-Sleep nach Inaktivität (spart Akku) - optional, kannst du auch auf "n" setzen
CONFIG_ZMK_SLEEP=y
